### ISSUE TITLE
Uninstalling the package deletes files needed for other packages

### ISSUE THREAD

**Issue by rosie607** [concrete5-community-store/community_store_abandoned_cart#3]
So I've done this a couple of times now and it's happened both times, if I uninstall this package it also deletes a bunch of files from the folder `/application/config/doctrine/proxies/` that are needed for the rest of the community store package.
This makes the whole community store package / any page with a community store block on error.
I kept a copy of these files this time and replacing makes the community store work again.
I've added a screen grab of the files it removes.

<img width="679" alt="screen shot 2018-03-01 at 10 49 58" src="https://user-images.githubusercontent.com/11563269/36840839-5a2f51f8-1d3e-11e8-90dd-f5220cf49246.png">

**Comment by Jozzeh** [comment]
Strange, I wonder if this also happens with other packages that require community store. 
As far as I know, no package has the ability to decide what is deleted when someone uninstalls the package... (although it has been some time since I worked with C5)

Does it happen when you check the "delete files" when uninstalling?  
Or does it also happens when you do not check the "delete files"-checkbox ?

**Comment by rosie607** [comment]
I did tick the box to remove the package files.
Yes this also seems to be happening if I uninstall another package. I tried uninstalling the Tiered Shipping Package and the same thing happened it also removed all the Community Store files from the proxies folder.

**Comment by Jozzeh** [comment]
I'll 'elevate' this issue to the base community store package so other people can have a look at it...  
This could be an error of the Concrete5 itself.
